.github/workflows/test.yaml, ngx-fudis/.eslintrc.json, ngx-fudis/.prettierignore, ngx-fudis/.prettierrc.json, ngx-fudis/angular.json, ngx-fudis/documentation.json, ngx-fudis/package-lock.json, ngx-fudis/package.json, ngx-fudis/projects/dev/.eslintrc.json, ngx-fudis/projects/dev/src/app/app.component.ts, ngx-fudis/projects/dev/src/app/app.module.ts, ngx-fudis/projects/dev/src/app/dialog-test/dialog-test-content/dialog-test-content.component.ts, ngx-fudis/projects/dev/src/app/dialog-test/dialog-test.component.ts, ngx-fudis/projects/dev/src/environments/environment.prod.ts, ngx-fudis/projects/dev/src/environments/environment.ts, ngx-fudis/projects/dev/src/index.html, ngx-fudis/projects/dev/src/main.ts, ngx-fudis/projects/dev/src/polyfills.ts, ngx-fudis/projects/ngx-fudis/.eslintrc.json, ngx-fudis/projects/ngx-fudis/schematics/ng-add/index.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/button/Button.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/button/public-api.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog-directives.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.ts, ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts, ngx-fudis/projects/ngx-fudis/src/public-api.ts, ngx-fudis/projects/ngx-fudis/src/test.ts
https://jira.funidata.fi/browse/DS-36
Tässä korjaantuu myös toi mainissa oleva `Button`-buildivirhe.
=> DS-36: Otetaan käyttöön ESLint

ngx-fudis/projects/foundations/spacing/readme.stories.mdx, ngx-fudis/projects/foundations/spacing/tokens.scss
First part of: https://jira.funidata.fi/browse/DS-39
=> DS-39: Add spacing tokens and basic docs

ngx-fudis/angular.json, ngx-fudis/projects/ngx-fudis/style.scss
Added Angular 13 storybook configuration to pull styles from style.scss file. Added import for global Fufis theme.
=> Storybook styles config

ngx-fudis/projects/ngx-fudis/src/lib/theme/fudis-theme.scss
Added pink default theme for broken build.
=> Added pink default theme to fix broken build

ngx-fudis/angular.json
Removed additional retrieve styles addition in angular.json
=> Removed styles config from angular.json

ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/mixins.scss, ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/readme.stories.mdx, ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/typography.stories.mdx
Created separate mdx typography documentation page that includes fudis typography levels for headings and body text.
=> Created typography documentation file

ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/typography.stories.mdx
Created unique typeset for all variations.
=> Changed typeset order

ngx-fudis/projects/ngx-fudis/src/lib/foundations/borders/readme.stories.mdx, ngx-fudis/projects/ngx-fudis/src/lib/foundations/borders/tokens.scss, ngx-fudis/projects/ngx-fudis/src/lib/foundations/colors/readme.stories.mdx, ngx-fudis/projects/ngx-fudis/src/lib/foundations/focus/readme.stories.mdx, ngx-fudis/projects/ngx-fudis/src/lib/foundations/spacing/readme.stories.mdx, ngx-fudis/projects/ngx-fudis/src/lib/foundations/spacing/tokens.scss
Täytettä Storybookin Foundationin alle.
Lisätty dokumentaatiota colors, focus, borders ja spacings -osioihin.
=> Storybook foundation documentation

ngx-fudis/projects/dev/src/app/app.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/fudis-text-input/text-input.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/fonts.scss, ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/mixins.scss, ngx-fudis/projects/ngx-fudis/src/lib/theme/ngMaterialCustomisation.scss
Ng serve spell didn't work, and got stuck without telling why. Reason was "fonts.scss" file where it couldn't go forward, as src was declared after font-style & weight. 🤷 CSS is awesome.
=> Ng serve fix

ngx-fudis/projects/dev/src/app/app.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/vanilla-text-area/vanilla-text-area.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/vanilla-text-area/vanilla-text-area.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/vanilla-text-area/vanilla-text-area.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/vanilla-text-area/vanilla-text-area.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/vanilla-text-area/vanilla-text-area.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts, ngx-fudis/projects/ngx-fudis/src/public-api.ts
https://jira.funidata.fi/browse/DS-50
=> DS-50: Vanilla textarea ver1

ngx-fudis/projects/dev/src/app/app.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/badge/badge.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/badge/badge.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/badge/badge.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/badge/badge.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/badge/badge.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/mixins.scss, ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/tokens.scss, ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts, ngx-fudis/projects/ngx-fudis/src/public-api.ts
https://jira.funidata.fi/browse/DS-64
Komponentti luotu ilman ngMaterialia, koska se ei tässä tuntunut järkevältä/tuovan mitään lisähyötyjä.
=> DS-64: Create Badge component

ngx-fudis/projects/dev/src/app/app.component.ts, ngx-fudis/projects/ngx-fudis/.eslintrc.json, ngx-fudis/projects/ngx-fudis/src/examples/form/radio-button-group-example/radio-button-group-example.component.html, ngx-fudis/projects/ngx-fudis/src/examples/form/radio-button-group-example/radio-button-group-example.component.scss, ngx-fudis/projects/ngx-fudis/src/examples/form/radio-button-group-example/radio-button-group-example.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/fudis-checkbox/fudis-checkbox.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/legend/legend.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button/radio-button.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button/radio-button.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button/radio-button.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button/radio-button.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/foundations/focus/mixins.scss, ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts, ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts, ngx-fudis/projects/ngx-fudis/src/public-api.ts
Created Radio-button-group-, radio-button, radio-button-group-example(for storybook testing purposes) and error message component.
=> Ds 53 component radio button group

ngx-fudis/angular.json
New angular component can be generate in components directory by using
ng generate component "name"
This will include component with sass file.
=> Added schematics to ngx-fudis

ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox/checkbox.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts
https://jira.funidata.fi/browse/DS-77
=> DS-77: Part 3 - Text input refactoring

ngx-fudis/.eslintrc.json, ngx-fudis/projects/dev/src/app/app.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts, ngx-fudis/projects/ngx-fudis/src/lib/types/icons.ts, ngx-fudis/projects/ngx-fudis/src/lib/types/lists.ts
https://jira.funidata.fi/browse/DS-77
=> DS-77: Part 4 - Text area

ngx-fudis/projects/dev/src/app/app.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox/checkbox.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/label/label.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/label/label.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/label/label.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/label/label.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/legend/legend.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts, ngx-fudis/projects/ngx-fudis/src/lib/theme/ngMaterialCustomisation.scss, ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts
https://jira.funidata.fi/browse/DS-77
- Dropdown refactoring
- Label component refactoring
=> DS-77: Part 5 - Dropdown

ngx-fudis/projects/dev/src/app/app.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/mixins.scss, ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/tokens.scss, ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts, ngx-fudis/projects/ngx-fudis/src/public-api.ts
https://jira.funidata.fi/browse/DS-81
=> DS-81: Fudis-link component

ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/label/label.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/label/label.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid.stories.ts
- Some styling adjustments from designer feedback
- Synced accessibility attributes with labels and inputs
=> Adjust fudis-label, guidance and accessibility attributes

ngx-fudis/projects/documentation/development/ComponentChecklist.stories.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/readme.mdx
https://jira.funidata.fi/browse/DS-98
=> DS-98: Body-text dokumentaatio + testit

ngx-fudis/.storybook/main.js, ngx-fudis/package-lock.json, ngx-fudis/package.json, ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox/checkbox.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid.stories.ts
https://jira.funidata.fi/browse/DS-74
Korjattu muutamat lisäosan tuomat herjat text-input, text-area ja radio-button-group komponenteista.
Herjaa vielä heittävät ao. komponentit:
Description-list
- Komponentin rakenne tällä hetkellä `<dl><div><dt><dd></dd></dt></div></dl>` joten lisäosa herjaa rakenteesta, koska dt pitäisi olla dl suora lapsi.
Checkbox ja Radio-button-group
- Herjaa, että samalla id:llä referoidaan useammassa ARIA linkityksessä. Veikkaan, että johtuu siitä miten storyt on rakennettu.
**Jos katselmoija ei keksi "nopeaa" ratkaisua näihin, niin näiden korjaus voisi sitten mennä ko. komponenttien _Testit ja dokumentaatio_-tiksujen piiriin.**
=> DS-74: Add accessibility addon for Storybook

ngx-fudis/projects/documentation/development/WaysOfWorking.stories.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/ngMaterial-theme.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox/checkbox.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts, ngx-fudis/projects/ngx-fudis/src/lib/theme/fudis-theme.scss, ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts, ngx-fudis/projects/ngx-fudis/src/public-api.ts, ngx-fudis/projects/ngx-fudis/style.scss
https://jira.funidata.fi/browse/DS-85
=> DS-85: Autocomplete

ngx-fudis/.storybook/preview.js, ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog-directives.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/readme.mdx
Lisätty readme filu ja siistitty storya.
En saanut dialogiesimerkkejä irtautettua toisistaan omiksi storyiksi, koska launcher component.
=> DS-84: Dialog documentation

ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/ngMaterial-theme.scss
https://jira.funidata.fi/browse/DS-84
=> DS-84: Dialog responsive styles

.github/workflows/publish.yaml, .github/workflows/test.yaml
Update ng15 CLI to 16 in GitHub Actions
=> Update ng15 to 16 in actions

ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/grid.directive.ts, ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/gridUtils.ts, ngx-fudis/projects/ngx-fudis/style.scss
Hot fixes to help Into development
=> Type and check fixes

ngx-fudis/projects/dev/src/app/app.component.html, ngx-fudis/projects/dev/src/app/app.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox/checkbox.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/datepicker/datepicker.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/datepicker/datepicker.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/datepicker/datepicker.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button/radio-button.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/directives/form/input-base/input-base.directive.ts, ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts
https://jira.funidata.fi/browse/DS-92
=> DS-92: Formcontrol typing v0.1

ngx-fudis/projects/dev/src/app/app.component.ts, ngx-fudis/projects/dev/src/assets/i18n/en.json, ngx-fudis/projects/dev/src/assets/i18n/fi.json, ngx-fudis/projects/ngx-fudis/src/lib/components/form/datepicker/datepicker.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts, ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts, ngx-fudis/projects/ngx-fudis/src/lib/utilities/config.service.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/utilities/config.service.ts, ngx-fudis/projects/ngx-fudis/src/public-api.ts
https://jira.funidata.fi/browse/DS-177
=> DS-177 adjust global configs

ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox/checkbox.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/datepicker/datepicker.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.service.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/grid-item/grid-item.directive.ts
https://jira.funidata.fi/browse/DS-180
=> DS-180: Fixes

ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/ngMaterial-theme.scss
https://jira.funidata.fi/browse/DS-180
=> DS-180: ngMaterial style override

ngx-fudis/projects/ngx-fudis/package-lock.json, ngx-fudis/projects/ngx-fudis/package.json, ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-term/description-list-item-term.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.service.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts, package-lock.json, package.json
=> DS-182: Fixes

ngx-fudis/projects/dev/src/app/app.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/types/miscellaneous.ts
Nimetty linkin näköinen haitari fudikseen expandable-liteksi. Saa keksiä paremman nimen jos tulee mieleen 😄
=> DS-144: Expandable: variant "Rajaustekijät"

ngx-fudis/projects/dev/src/app/components/formExamples.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button/radio-button.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button/radio-button.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button/radio-button.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/directives/form/fieldset-base/fieldset-base.directive.ts, ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts
https://jira.funidata.fi/browse/DS-101
=> DS-101: Radio-button/Radio-button-group, tests & documentation

ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/heading.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/heading.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/heading.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/heading.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/readme.mdx
https://jira.funidata.fi/browse/DS-99
=> DS-99: Heading, tests & documentation

ngx-fudis/projects/ngx-fudis/src/lib/components/form/label/label.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/label/label.component.ts
https://jira.funidata.fi/browse/DS-183
Label on Fudiksen sisäisen komponentti, joten sille ei ole Storybook dokumentaatiota/readme -tiedostoa.
Lisätty muutama perus yksikkötesti. En nähnyt vaivan arvoiseksi yrittää testata `for` -attribuutin toimintaa.
=> DS-183: Label, tests & documentation

ngx-fudis/projects/ngx-fudis/src/lib/components/badge/badge.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/badge/badge.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/badge/readme.mdx
https://jira.funidata.fi/browse/DS-93
=> DS-93: Badge, tests & documentation

ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/ngMaterial-theme.scss
https://jira.funidata.fi/browse/DS-191
=> DS-191: adjust datepicker focus styles

ngx-fudis/projects/dev/src/app/components/formExamples.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
https://jira.funidata.fi/browse/DS-114
Error summary kirjoitettu vähän mututuntumalta, sitä ja kaikkea muutakin voi täydentää jos koetaan tarpeelliseksi.
=> DS-114: Expandable: testit & dokumentaatio

ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-term/description-list-item-term.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-term/description-list-item-term.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group.service.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group.service.ts, ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts, ngx-fudis/projects/ngx-fudis/src/public-api.ts
https://jira.funidata.fi/browse/DS-208
=> DS-208: Add language config service for Language Badge Group

ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.ts, ngx-fudis/projects/ngx-fudis/src/public-api.ts
https://jira.funidata.fi/browse/DS-208
Feedback from Slack: https://sisudev.slack.com/archives/C03G46K6LG1/p1690541786194129
=> DS-208: Export atLeastOneRequired validator

ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/directives/content-projection/actions/actions.directive.ts
https://jira.funidata.fi/browse/DS-208
From HDM feedback: https://sisudev.slack.com/archives/C03G46K6LG1/p1690545106291069
=> DS-208: Add actions to Section component

ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.stories.ts
https://jira.funidata.fi/browse/DS-197
Not most elegant solution, but as schedule is now tight it should work. But I am strongly leaning towards refactoring these components to not use ngMaterial.
=> DS-197: Pre-selected options for ngMaterial dropdowns

ngx-fudis/projects/ngx-fudis/karma.conf.js, ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert-group/alert-group.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert-group/alert-group.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert-group/alert-group.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert/alert.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert/alert.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert/alert.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/alert/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/services/alert/alert.service.spec.ts, ngx-fudis/projects/ngx-fudis/utilities/tests/utilities.ts
https://jira.funidata.fi/browse/DS-147
=> DS-147: Alert & Alert Service, Part 3: Tests

ngx-fudis/projects/ngx-fudis/package-lock.json, ngx-fudis/projects/ngx-fudis/package.json, ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select-selected-item-chip/autocomplete-multi-select-selected-item-chip.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select-selected-item-chip/autocomplete-multi-select-selected-item-chip.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.component.ts, package-lock.json, package.json
Added optionChange emit for chip-item deletion and some refactoring/cleaning.
Version bump for new release.
=> [HOTFIX]: Autocomplete fix + version bump

ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/ngMaterial-theme.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.spec.ts
Placeholder: https://sisudev.slack.com/archives/C04NE2ZPZST/p1695996448795909
DD: https://sisudev.slack.com/archives/C03G46K6LG1/p1696845224870379
=> [Dropdown & DD]: form placeholder styles and dd whitespace fix

ngx-fudis/projects/dev/src/app/components/formExamples.component.ts, ngx-fudis/projects/documentation/development/CreatingARelease.stories.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.ts, ngx-fudis/projects/ngx-fudis/src/public-api.ts
- Renaming validator stuff for consistency between Fudis and Sisu
- Adjust markAsTouched logic in Checkbox Group
- Adjust Error Message
=> [Validators / Checkbox Group]: Renaming & markAsTouched logic changes

ngx-fudis/package-lock.json, ngx-fudis/package.json, ngx-fudis/projects/ngx-fudis/package-lock.json, ngx-fudis/projects/ngx-fudis/package.json, package-lock.json, package.json
=> Bump to version v0.1.3

ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.ts
https://jira.funidata.fi/browse/DS-227
=> [Validators]: Unit tests and documentation for Fudis Validators

ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/getValidators.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/getValidators.ts
- Added basic unit tests to getValidators.ts utility functions
=> [getValidators]: add tests

ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-group/select-group.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-group/select-group.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-group/select-group.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-option/multiselect-option.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.stories.ts
https://jira.funidata.fi/browse/DS-228
Unit tests for select group component.
Additionally:
Removed unnecessary Inputs from select group component. Fixed typos in select component story. Also fixed visibility hidden in multiselect scss file.
=> [SelectGroupComponent]: Unit tests

ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/mock_data.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-group/select-group.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-option-base/select-option-base.directive.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-option-base/select-option-base.directive.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/selectUtilities.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-option/multiselect-option.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.ts
https://jira.funidata.fi/browse/DS-228
Unit tests for testing Select components basic functionality. 
Mock components include test scenarios for Fudis Multi Select and Multi Select Autocomplete components.
Also fixed some bugs related to not showing options in non-autocomplete component, and issues with triggering blur events.
=> [SelectBaseDirective]: Unit tests

ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/autocomplete/autocomplete.component.spec.ts
https://jira.funidata.fi/browse/DS-228
This pull request consists of select autocomplete tests, mainly focusing on testing autocomplete focus and blur trigger functionality. Some of the Inputs are tested as a part of other select component directives and tests. Including placeholder, autocompleteClearButton in select base directive tests.
=> [Select]: Autocomplete unit tests

ngx-fudis/projects/ngx-fudis/src/lib/components/badge/badge.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/badge/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs-item/breadcrumbs-item.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/button/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/dropdown-menu/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/footer/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/notification/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/directives/spacing/spacing.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/readme.mdx
Jira-ticket: https://funidata.atlassian.net/browse/DS-240
- TODO comments added. 
- Fixed broken storybook 'show code' preview windows. 
- Wrong imports fixed
- View Story Controls enhancement
- Removed deprecated documentation
- Fixed Storybook documentation links
No major findings.
=> [Badge, Breadcrumbs, Button]: Checking for 1.0

ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
Jira-ticket: https://funidata.atlassian.net/browse/DS-240
Minor cleaning and adding TODO comments
=> [Dialog]: Checking for 1.0

ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/directives/dialog/dialog-directives.ts
Jira-ticket: https://funidata.atlassian.net/browse/DS-240
Added TODOs and adjusted Storybook docs
=> [Expandable]: Checking for 1.0

ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts, ngx-fudis/projects/ngx-fudis/src/lib/services/breakpoint/breakpoint.service.ts, ngx-fudis/projects/ngx-fudis/src/lib/services/focus/focus.service.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/services/focus/focus.service.ts, ngx-fudis/projects/ngx-fudis/src/lib/services/form/error-summary/error-summary.service.ts, ngx-fudis/projects/ngx-fudis/src/lib/services/form/error-summary/internal-error-summary.service.ts, ngx-fudis/projects/ngx-fudis/src/lib/services/grid/grid.service.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/services/grid/grid.service.ts, ngx-fudis/projects/ngx-fudis/src/public-api.ts
https://funidata.atlassian.net/browse/DS-240
Updated some internal documentation and added TODOs for missing tests and Storybook documentation.
Removed Error Summary Component from public API.
=> [Breakpoint, Focus, Grid and Error Summary Services]: Checking for 1.0

ngx-fudis/projects/ngx-fudis/src/lib/components/badge/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs-item/breadcrumbs-item.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/button/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/directives/form/fieldset-base/fieldset-base.directive.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/directives/form/fieldset-base/fieldset-base.directive.ts, ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/getValidators.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/getValidators.ts, ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
Jira-ticket: https://funidata.atlassian.net/browse/DS-252
- added min > 0 logic check for Checkbox Group's hasRequired check
- move titleSize away from FieldsetBase to FieldsetComponent
=> [BreadCrumbsComponent, CheckboxGroupComponent]: API and controls check for Breadcrumbs and Checkbox Group

ngx-fudis/projects/ngx-fudis/src/lib/services/translation/readme.stories.mdx
Added missing documentation for Translation Service
=> [Translation Service]: Documentation

ngx-fudis/package-lock.json, ngx-fudis/package.json, ngx-fudis/projects/ngx-fudis/package-lock.json, ngx-fudis/projects/ngx-fudis/package.json, package-lock.json, package.json, test/package-lock.json, test/package.json
https://funidata.atlassian.net/browse/DS-252
Creating prepatch version with `npm version prepatch --preid=rc` in order to test this prerelease in Sisu.
=> Bump to version v0.2.3-rc.0

.github/workflows/release.yaml, ngx-fudis/package-lock.json, ngx-fudis/package.json, ngx-fudis/projects/ngx-fudis/package-lock.json, ngx-fudis/projects/ngx-fudis/package.json, package-lock.json, package.json, test/package-lock.json, test/package.json
https://funidata.atlassian.net/browse/DS-252
Creating prepatch version with `npm version prepatch --preid=rc` in order to test this prerelease in Sisu.
=> Bump to version v0.2.4-rc.0

ngx-fudis/package-lock.json, ngx-fudis/package.json, ngx-fudis/projects/dev/src/app/app.component.html, ngx-fudis/projects/dev/src/app/app.module.ts, ngx-fudis/projects/dev/src/app/components/examplePage.component.html, ngx-fudis/projects/dev/src/app/components/examplePage.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
https://funidata.atlassian.net/browse/DS-273
Added support for UI Router.
Created some dummy example pages for sandbox to test router in action.
=> DS-273: Added UI Router support

ngx-fudis/package-lock.json, ngx-fudis/package.json, ngx-fudis/projects/ngx-fudis/package-lock.json, ngx-fudis/projects/ngx-fudis/package.json, package-lock.json, package.json, test/package-lock.json, test/package.json
https://funidata.atlassian.net/browse/DS-273
Created new pre patch to test in Sisu
=> Bump to version v0.2.4

ngx-fudis/projects/dev/src/app/app.component.html, ngx-fudis/projects/dev/src/app/app.component.ts, ngx-fudis/projects/dev/src/app/app.module.ts, ngx-fudis/projects/dev/src/app/dialog-test/dialog-test-content/dialog-test-form.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert-group/alert-group.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert/alert.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.docs.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/services/dialog/dialog.service.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/services/dialog/dialog.service.ts
Adjusted Dialog close functions
- closing all Dialog instances with `closeAll()`
- closing opened Dialog with optional result parameter with `close(result)`
Also updated Dialog docs accordingly.
=> [DialogService]: Close function with parameter to be passed back to the component

ngx-fudis/package-lock.json, ngx-fudis/package.json, ngx-fudis/projects/ngx-fudis/package-lock.json, ngx-fudis/projects/ngx-fudis/package.json, package-lock.json, package.json, test/package-lock.json, test/package.json
Bump patch version to test improvements and fixes in Sisu.
=> Bump to version v0.2.7

ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/notification/nofication.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification.component.ts
Fixed a bug in Link, when External link's title was only one word.
Also adjusted onPushDetection on several static components.
=> [Link]: Bug fix on external link parsing

ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary-component.docs.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.docs.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/directives/form/fieldset-base/fieldset-base.directive.ts, ngx-fudis/projects/ngx-fudis/src/lib/directives/form/form-actions/form-actions.docs.mdx, ngx-fudis/projects/ngx-fudis/src/lib/directives/form/input-base/input-base.directive.ts, ngx-fudis/projects/ngx-fudis/src/lib/services/form/error-summary/error-summary-service.docs.mdx
Jira ticket: https://funidata.atlassian.net/browse/DS-274
General cleaning and improving documentation.
=> [Form components and services]: Update docs, comments and adjust internal renaming

ngx-fudis/projects/ngx-fudis/src/lib/theme/fudis-theme.scss
https://funidata.atlassian.net/browse/DS-274
Added rem-multiplier to ngMaterial typography config.
=> [NgMaterial theme]: Typography size conversion

ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group-with-form-array.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group-with-form-group.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.docs.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/directives/form/fieldset-base/fieldset-base.directive.ts, ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts, ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/getValidators.ts
Jira ticket: https://funidata.atlassian.net/browse/DS-274
Adds support for FormArrays in CheckboxGroup to enable testing it in Sisu.
TODO in another PR:
- Update Storybook docs
- Update tests with FormArray cases (Guidance and Checkbox, CheckboxGroup)
- In general check code through, clean and add comments
=> [CheckboxGroup]: Add support for FormArray

ngx-fudis/package-lock.json, ngx-fudis/package.json, ngx-fudis/projects/ngx-fudis/package-lock.json, ngx-fudis/projects/ngx-fudis/package.json, package-lock.json, package.json, test/package-lock.json, test/package.json
https://funidata.atlassian.net/browse/DS-274
Testing release 0.2.8
=> Bump to version v0.2.8

ngx-fudis/package-lock.json, ngx-fudis/package.json, ngx-fudis/projects/ngx-fudis/package-lock.json, ngx-fudis/projects/ngx-fudis/package.json, package-lock.json, package.json, test/package-lock.json, test/package.json
Bump patch version to test fixes in Sisu.
=> Bump to version v0.2.9

ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group-with-form-group.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.ts
Jira ticket: https://funidata.atlassian.net/browse/DS-274
To enable cases, where CheckboxGroup is built without using FormArray or FormGroup.
=> [Checkbox, CheckboxGroup]: add formControl option to Checkbox

ngx-fudis/package-lock.json, ngx-fudis/package.json, ngx-fudis/projects/ngx-fudis/package-lock.json, ngx-fudis/projects/ngx-fudis/package.json, package-lock.json, package.json, test/package-lock.json, test/package.json
=> Bump to version v1.0.0

ngx-fudis/package-lock.json, ngx-fudis/package.json
=> [Ui-router]: Remove repedencies

ngx-fudis/package-lock.json, ngx-fudis/package.json, ngx-fudis/projects/ngx-fudis/package-lock.json, ngx-fudis/projects/ngx-fudis/package.json, package-lock.json, package.json, test/package-lock.json, test/package.json
=> Bump to version v1.1.0-rc.0

ngx-fudis/package-lock.json, ngx-fudis/package.json, ngx-fudis/projects/ngx-fudis/package-lock.json, ngx-fudis/projects/ngx-fudis/package.json, package-lock.json, package.json, test/package-lock.json, test/package.json
=> Bump to version v1.1.0

ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-term/description-list-item-term.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-option/multiselect-option.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/services/id/id.service.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/services/id/id.service.ts, ngx-fudis/projects/ngx-fudis/src/lib/services/translation/readme.stories.mdx, ngx-fudis/projects/ngx-fudis/src/lib/services/translation/translation.service.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/services/translation/translation.service.ts
Jira ticket: https://funidata.atlassian.net/browse/DS-257
=> [Translation Service]: Unit tests, docs update and minor refactoring and renaming

ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.docs.mdx
Added missing required input property to expandable documentation
=> [Documentation, Expandable]: Add required input property to expandable documentation

settings/.vscode/extensions.json
Jira Ticket: https://funidata.atlassian.net/browse/OTM-31207
=> [Workspace settings]: add angular ng-template to recommendations

ngx-fudis/projects/ngx-fudis/src/lib/foundations/spacing/classes.scss, ngx-fudis/projects/ngx-fudis/src/lib/foundations/spacing/mixins.scss, ngx-fudis/projects/ngx-fudis/src/lib/theme/component-themes-to-apply.scss, ngx-fudis/projects/ngx-fudis/src/lib/theme/display-theme.scss
=> [Spacing]: Helper classes

ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.stories.ts
https://funidata.atlassian.net/browse/DS-364
Removing marginTop and marginBottom property. Replaced marginTop styling in nested section story with Fudis CSS Helper classes.
=> [Section]:Removed marginTop and Bottom

ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/readme.mdx
https://funidata.atlassian.net/browse/DS-365
Removed marginTop and marginBottom Grid Inputs from Fieldset component.
=> [Fieldset]:Removed marginTop and Bottom Input

ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form-dynamic-validators.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.html, ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select-showcase.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
https://funidata.atlassian.net/browse/DS-366
Removed marginBottom and Top input and changed related stories to use Fudis CSS Helper classes
=> [Form]: Removed marginTop and Bottom input

ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/ngMaterial-theme.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/components/form/label/label.component.scss, ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/mixins.scss, ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/tokens.scss
https://funidata.atlassian.net/browse/DS-355
Rename and unify typography tokens from single char to double char, e.g. `$heading-l-font-size` --> `$heading-lg-font-size`
=> [Typography]: Unify size syntax

ngx-fudis/projects/ngx-fudis/package.json
https://funidata.atlassian.net/browse/DS-377
=> [Chore]: Fix Fudis homepage in project's package.json

.github/workflows/cla.yaml
=> Add marisanity to CLA allowlist and remove xanxan

ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog-directives.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog-directives.ts, ngx-fudis/projects/ngx-fudis/src/lib/directives/form/form-actions/form-actions.directive.ts, ngx-fudis/projects/ngx-fudis/src/lib/utilities/dialog/dialog-utils.ts
https://funidata.atlassian.net/browse/DS-422
Prevent closing a dialog through `FormSubmitDirective` and `DialogCloseDirective` if the button has been disabled.
=> [Dialog]: Prevent closing a dialog if the button is disabled

ngx-fudis/package-lock.json, ngx-fudis/package.json, ngx-fudis/projects/ngx-fudis/package-lock.json, ngx-fudis/projects/ngx-fudis/package.json, package-lock.json, package.json, test/package-lock.json, test/package.json
https://funidata.atlassian.net/browse/DS-458
=> Bump to version v5.0.0

ngx-fudis/projects/ngx-fudis/src/lib/services/dialog/dialog.service.ts
Add a possibility to type the MatDialogConfig, and service function arguments for close and open.
=> [DialogService]: Add typings to functions

ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable-content.directive.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable-content.directive.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer-content.directive.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.component.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset-content.directive.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset-content.directive.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form-content.directive.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form-content.directive.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/section/section-content.directive.spec.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/section/section-content.directive.ts, ngx-fudis/projects/ngx-fudis/src/lib/types/miscellaneous.ts
https://funidata.atlassian.net/browse/DS-264
Created a new type fudisFieldsetActionsAlign.
Improved content directives unit test to check host classes.
=> [Expandable, Fieldset, Footer, Form, Section]:Content projection directives unit tests

ngx-fudis/package-lock.json, ngx-fudis/package.json, ngx-fudis/projects/ngx-fudis/package-lock.json, ngx-fudis/projects/ngx-fudis/package.json, package-lock.json, package.json, test/package-lock.json, test/package.json
https://funidata.atlassian.net/browse/DS-498
Bump to version v5.1.0
=> Bump to version v5.1.0

ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/examples/fieldset-example.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/common.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.stories.ts, ngx-fudis/projects/ngx-fudis/src/lib/components/notification/readme.mdx, ngx-fudis/projects/ngx-fudis/src/lib/components/tab-navigation/tab-navigation.mdx, ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
https://funidata.atlassian.net/browse/DS-477
Hide private Tab Navigation methods from Storybook documentation. 
Also checked various other component's controls tab and ArgTables. Ensured that provided controls were meaningful.
=> [Chore]: Cleaning Storybook documentation

ngx-fudis/package-lock.json, ngx-fudis/package.json, ngx-fudis/projects/ngx-fudis/package-lock.json, ngx-fudis/projects/ngx-fudis/package.json, package-lock.json, package.json, test/package-lock.json, test/package.json
https://funidata.atlassian.net/browse/DS-511
=> Bump to version v5.1.1

test/visual-regression/error-summary.spec.ts, test/visual-regression/form-dynamic-validators.spec.ts
Fix e2e-tests that were flaky.
=> Fix flaky e2e-tests

ngx-fudis/package-lock.json, ngx-fudis/package.json, ngx-fudis/projects/ngx-fudis/package-lock.json, ngx-fudis/projects/ngx-fudis/package.json, package-lock.json, package.json, test/package-lock.json, test/package.json
https://funidata.atlassian.net/browse/DS-525
=> Bump to version v5.1.2

ngx-fudis/package-lock.json, ngx-fudis/package.json, ngx-fudis/projects/ngx-fudis/package-lock.json, ngx-fudis/projects/ngx-fudis/package.json, package-lock.json, package.json, test/package-lock.json, test/package.json
Prerelease for testing new peerDependency semver syntax.
=> Bump to version v6.0.0-rc.0

.github/dependabot.yaml, .github/workflows/publish_docs_from_pr.yaml
https://funidata.atlassian.net/browse/DS-555
Removed redundant docker check from root. Ignored major updates also from Docker-files.
=> [Debendabot]: Configure debendbot yaml

.github/workflows/cla.yaml
Add marisanity temporarily to allowlist until we have merged all the PR's she has opened.
=> [CLA]: Add developer (temporary)
