funidata/fudis

ngx-fudis/.stylelintrc.json
ngx-fudis/package-lock.json
ngx-fudis/package.json
ngx-fudis/projects/dev/src/app/app.scss
ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.scss
ngx-fudis/projects/ngx-fudis/src/lib/components/form/fudis-text-input/text-input.component.scss
ngx-fudis/projects/ngx-fudis/src/lib/foundations/focus/mixins.scss
ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/fonts.scss
ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/mixins.scss
ngx-fudis/projects/ngx-fudis/src/lib/theme/ngMaterialCustomisation.scss

Stylelint doesn't provide a way to define in which order CSS properties are listed and with guidelines plugin even forces alphabetical order. This plugin sets and lints the order in an opinionated "as it should be" order.

Install stylelint-config-concentric-order

---

ngx-fudis/projects/dev/src/app/app.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button/radio-button.component.html

https://github.com/angular/angular/issues/11757
Issue replication without this PR:
In storybook radiobutton example: tab from first group to the second group. Make a selection and then shift+tab to previous group, earlier it selected the last item and not the checked item.
Also added labelled-by attributes so screen reader reads the legend as well.

Workaround for name issue with ng forms and radiobuttons

---

ngx-fudis/projects/dev/src/app/app.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button/radio-button.component.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.scss
ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.stories.ts
ngx-fudis/projects/ngx-fudis/src/test.ts

https://jira.funidata.fi/browse/DS-79
Lisätty sääntö, että testeissä ei saa enää tulla seuraavanlaisia virheitä (buildi ei mene läpi jos näitä virheitä löytyy):
```
- NG0303: Can't bind to ‘xxx’ since it isn't a known property of ‘xxx’
- NG0304: ‘xxx’ is not a known element
```

DS-79: Numerovalitsimen lisäys text-inputtiin + testien korjailuja

---

ngx-fudis/projects/documentation/development/CreatingAComponent.stories.mdx
ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.scss
ngx-fudis/projects/ngx-fudis/src/lib/components/button/readme.mdx
ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.component.scss
ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.scss
ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/notification/nofication.component.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification.component.scss
ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification.component.stories.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/notification/readme.mdx
ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.scss
ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.stories.ts
ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/mixins.scss
ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
ngx-fudis/projects/ngx-fudis/src/public-api.ts

Luotiin notifikaatio komponentti, sekä siihen liittyvät testit ja storybook dokumentaatio.Notifikaation testit testaavat vain komponentin luokkanimiä. 
Lisäksi:
Link component:
- Lisättiin color proppi, jonka avulla voidaan vaihtaa linkin väriä tarvittaessa (esim. notifikaation linkki aina tumman harmaa).
- External ikoni komponentti ottaa vastaan myös color propsin.
Body text componentti:
- poistettiin margin-bottom typografia mixineistä.
- Lisättiin margin-bottom propsi, jonka default on 0.
- Muutettiin komponentin dokumentaatiota, jotta pystyttiin paremmin demoamaan uudet margin-bottom koot 0,m, ja l. (Huom! kokoa s ei ole figma suunnitelmissa, mutta mahdollisesti tehdään myöhemmin).
- Lisättiin luokka fudis-body-text__paragraph. Tekstiin joukkoon lisättävä linkki komponentti saa …

Ds 73 fudis notification

---

.github/workflows/complete_storybook_deployment.yaml
.github/workflows/storybook_publish.yaml

- Currently the deployment environments are be updated with `success` status and URL before the deployment has actually finished. This PR moves the status updates to run after the `pages-build-deployment` workflow. Now PR's won't include broken URL's and reflect the deployment status more accurately.

Fix Storybook deployment environments' status updates

---

ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox/checkbox.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox/checkbox.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/directives/form/input-base/input-base.directive.ts

Lisätty "initialFocus" @Input-direktiivi peruslomakekomponenteille, jolla voidaan siirtää kohdistus kenttään, kun komponentti ladataan ensimmäisen kerran kälissä.
https://jira.funidata.fi/browse/DS-192

DS-192: Add initial focus to form components

---

ngx-fudis/projects/dev/src/app/app.component.html
ngx-fudis/projects/dev/src/app/app.module.ts
ngx-fudis/projects/dev/src/app/components/dropdownExamples.component.html
ngx-fudis/projects/dev/src/app/components/dropdownExamples.component.ts
ngx-fudis/projects/dev/src/app/components/formExamples.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid/grid.component.scss
ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/grid-api/grid-api.directive.ts

https://jira.funidata.fi/browse/DS-198
Bug mentioned in the ticket seems to be caused by ngMaterial, as it stretches elements too wide and we don't have feasible way to restrict that.
Problem should diminish if we refactor ngMaterial dropdowns away to use our own components and subcomponents. Meanwhile this fix should not cause other arm elsewhere.

DS-198: Adjust minWidth of grid items

---

ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.stories.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.stories.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.scss
ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.scss

From feedback requests:
- Add placeholder `@Input` to Autocomplete Multiselect [(Slack-thread)](https://sisudev.slack.com/archives/C04NE2ZPZST/p1695996448795909)
- Add placeholder `@Input` to Autocomplete Singleselect [(Slack-thread)](https://sisudev.slack.com/archives/C04NE2ZPZST/p1695996448795909)
- Fix margin bug in Notification by resetting margins in BodyText [(Slack-thread)](https://sisudev.slack.com/archives/C03G46K6LG1/p1696233432331349)

[IMPROVEMENT / Autocomplete single & multiselect]: Add placeholder prop

---

ngx-fudis/projects/ngx-fudis/src/lib/components/badge/badge.component.scss
ngx-fudis/projects/ngx-fudis/src/lib/foundations/spacing/tokens.scss

https://sisudev.slack.com/archives/C04NE2ZPZST/p1697462182558299
Badge split in to two rows in small screen. Fixed by adding `display: inline-block;`

[BadgeComponent]: Add CSS display

---

ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert-group/alert-group.component.html

Alert Group's `aria-label` was present always, even if there were zero alerts to inform about. 
Let's initiate _"Notifications - number of notifications: 0"_ only when there are 1 or more alert present.

[Alert Group]: Initiate aria-label only when there are 1 or more alert present

---

ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.scss

Change fudis-link color to `primary-color-dark` as in Sisu.
Change is communicated with designers.

[Link]: Change color to primary-dark

---

ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/autocomplete/autocomplete.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-option-base/select-option-base.directive.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.ts

https://jira.funidata.fi/browse/DS-228
- Fixed a bug, where "No results found" text didn't work properly if control value passed from application didn't match with any of the actual options
- Adjusted logic on when dropdown opens on focus with autocomplete

[Select]: Adjust autocomplete no results found logic

---

ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.scss
ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.stories.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/ngMaterial-theme.scss
ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/readme.mdx

Added new `size` option `xl` for Dialog component.
This was a request from development team.
Note that `xl` is initially the same size as `lg` but `xl` will hold its width longer, therefore it's wider in smaller screens.
[Figma designs](https://www.figma.com/file/kqoga9Si2O2KmUDGVcpBep/HRP-353-Harjoitteluraportit?type=design&node-id=133-7021&mode=design&t=tvUUmhGkzGXM8JtV-0) were 1100px wide and tried to follow them as closely as possible --> both `lg` and `xl` are 1120px when most widest.

[Dialog]: Add dialog size 'xl'

---

.prettierrc
.prettierrc.yaml
cypress/tsconfig.json
ngx-fudis/.storybook/tsconfig.json
ngx-fudis/package-lock.json
ngx-fudis/package.json
ngx-fudis/tsconfig.json
package-lock.json
package.json

Explicitly use JSON parser for formatting `tsconfig.json` files to avoid the problems described here: https://github.com/prettier/prettier/issues/15942

Fix problems with Prettier's parsing of tsconfig.json files

---

ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.stories.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.stories.ts
ngx-fudis/projects/ngx-fudis/src/lib/directives/form/fieldset-base/fieldset-base.directive.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/directives/form/input-base/input-base.directive.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/foundations/utilities/classes.scss

https://jira.funidata.fi/browse/DS-195
_Extra:_
Noticed that both `text-input` and `text-area` components were missing disabled state styles. `Text-area` was also missing invalid state styles. This was noticed since I wanted to test disabled state CSS class passing in `InputBaseDirective` unit tests.

[InputBaseDirective, FieldsetBaseDirective]: Unit tests

---

ngx-fudis/projects/dev/src/app/app.component.html
ngx-fudis/projects/dev/src/app/components/formExamples.component.html
ngx-fudis/projects/dev/src/app/components/formExamples.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.stories.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.stories.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts

Jira ticket: https://funidata.atlassian.net/browse/DS-274
To enable focusing from Error Summary to corresponding form fields, if Fudis application does not use Angular Router.

[Form, ErrorSummary]: Add onClick link type to support non Angular Router apps

---

ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts

In previous PR both formArray and formGroup were marked as required inputs, which was unintentional.

[CheckboxGroup]: Remove required props

---

ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid/grid.component.scss
ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/heading.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/directives/link/link.directive.ts
ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts

- Adjust encapsulation and CSS grid-column logic
- This should help in .fudis-heading CSS scope issue in client app
- Adjust Storybook docs excludes

[HeadingComponent]: Adjust encapsulation and CSS grid-column logic

---

ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group.component.scss
ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group.component.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge/language-badge.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge/language-badge.component.scss
ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge/language-badge.component.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge/language-badge.component.ts

Jira ticket: https://funidata.atlassian.net/browse/DS-265
General checking for Language Badge and Language Badge Group
- Unit tests
- Adjusted CSS: Matched Language Badges heigth with DL Term height
- Some other cleaning and tweaking

[Language Badge, Language Badge Group]: Check for 1.2 release

---

ngx-fudis/projects/ngx-fudis/_index.scss
ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-docs.mdx

- Included Spacing classes file as forwarded file in _index.scss
- Fixed Documentation of Description List Sub-heading usage

[Spacing Classes, DL docs]: Few fixes

---

ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/gridUtils.ts
ngx-fudis/projects/ngx-fudis/src/lib/utilities/rem-converter.ts

Because Funidata's Sisu's test tools use older EcmaScript configs it causes all Grid related unit tests to fail, because GridUtils used JavaScript replaceAll function. Did minor refactoring and added additional checks to replace replaceAll with alternative solution.

[GridUtils]: Adjust replaceAll logic

---

ngx-fudis/projects/dev/src/app/components/formExamples.component.html
ngx-fudis/projects/dev/src/app/dialog-test/dialog-test-content/dialog-test-form.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.docs.mdx
ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.stories.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.stories.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.docs.mdx
ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts

Jira ticket: https://funidata.atlassian.net/browse/DS-312
As router configs vary in Funidata's applications, it was discussed that for Error Summary onClick linkType just seems to work best with all varying configs. So now Error Summary implements just that and other options are removed.
Breaking:
- Form component does not have anymore errorSummaryLinkType input property

[Form, ErrorSummary]: Remove errorSummaryLinkType

---

.github/workflows/release.yaml

- The 3rd-party `irongut/editrelease` workflow appears to have stopped working somewhere between testing and the last release. It was used to add a link to the deployed documentation to respective release notes. Removed to keep things running smoothly.
- The root index.html file at fudis.funidata.fi was subject to AWS's default cache control (which is between zero seconds and a year at their discretion) causing lingering redirects to a previous documentation version. Now using a TTL of 5 seconds when uploading the redirection index.html. See [AWS docs here](https://docs.aws.amazon.com/whitepapers/latest/build-static-websites-aws/controlling-how-long-amazon-s3-content-is-cached-by-amazon-cloudfront.html#specify-cache-control-headers).

Fix docs deploy workflow failing when editing release notes programmatically and set low TTL for root index.html cache

---

ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.scss

https://funidata.atlassian.net/browse/DS-338
Height on checkbox label produced a overflow bug. Fixed by setting a min-height instead of static height value.

[Checkbox]: Changed checkbox height to min height

---

ngx-fudis/projects/dev/src/styles.scss
ngx-fudis/projects/documentation/introduction/GettingStarted.stories.mdx
ngx-fudis/projects/ngx-fudis/src/lib/theme/palette.scss
ngx-fudis/projects/ngx-fudis/style.scss

Jira-ticket: https://funidata.atlassian.net/browse/DS-380
BREAKING CHANGE:
- Application can remove now previously instructed lines from their main CSS file: 
`@use '@angular/material' as mat;`
`@include mat.core();`
unless application has their own additional ngMaterial uses outside Fudis.
Although style bundle of Fudis has worked well so far, it had unnecessary "double imports" on some styles. Biggest bundle bloater came from Fudis +  Angular Material imports. Instructions and Storybook have been now adjusted to avoid double import of ngMaterial.
This is marked as Breaking Change, as previously we have instructed applications to import both Fudis and ngMaterial in the root style file, but now importing ngMaterial should be unnecessary.

[SCSS]: Style import optimizations 

---

ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.ts

When clicking disabled Select's chevron or search icon it caused `Cannot read properties of undefined (reading inputRef)` error. To avoid this, added disabled control check for the mouseUp event listener.

[SelectBase]: Undefined inputRef error

---

ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/directives/form/text-field-component-base/text-field-component-base.directive.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/directives/form/text-field-component-base/text-field-component-base.directive.ts
ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts

With TextInput and TextArea, if user clears the input field, it will set the FormControl value as null instead of an empty string. Client application has now need for not setting the value as null and accepting empty string as control's value.
This PR adds new `nullControlOnEmptyString` property to TextInput and TextArea, which prevents automatic nulling of control's value.
Internally also refactored TextArea and TextInput to inherit new TextFieldComponentBaseDirective to avoid duplicate code, as components share lots of same logic and variables etc.
In following PR we should write more throughout tests to this new Directive, although through TextInput, TextArea and e2e tests most of the functionality is quite well already covered.

[TextFieldComponentBaseDirective]: New internal Directive and nullControlOnEmptyString property

---

ngx-fudis/projects/dev/src/app/app.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert.mdx
ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.html

https://funidata.atlassian.net/browse/DS-355
- Added documentation for using `<fudis-alert-group />` in the application template.
- Moved AlertGroup to the bottom element of Dialog Component

[AlertGroup]: Missing documentation about template usage

---

ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/ngMaterial-theme.scss
ngx-fudis/projects/ngx-fudis/src/lib/directives/tooltip/ngMaterial-theme.scss

https://funidata.atlassian.net/browse/DS-355
Certain typography styles did not reflect correctly in customer (Sisu) application side. This might be due to Material 3 update where most of the typography configs were removed and M3 did not have clear instructions how to set up custom typography for individual components.
To fix the issue, some typography styles are overwritten in Datepicker and Tooltip components'  respective `ngMaterial-theme.scss` files. These changes should not effect the components in any way in Fudis.

[Datepicker, Tooltip]: Angular Material based components not reflecting all styles correctly in customer app

---

ngx-fudis/projects/ngx-fudis/package.json
package.json

https://funidata.atlassian.net/browse/DS-356
https://www.npmjs.com/package/@funidata/ngx-fudis did not list **repository** nor **homepage** information in the info sidepanel.
- Moved _repository_, _bugs_ and _homepage_ from root `package.json` to projects/ngx-fudis `package.json`
- Copied _author_ to be in both `package.json` files
- Added keywords

[Maintenance]: Missing information in npmjs website

---

ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/services/dialog/dialog.service.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/services/dialog/dialog.service.ts

Slack discussion: https://sisudev.slack.com/archives/C8UPGUKJL/p1733147123932459
App developers encountered error, as they are asking Dialog service to close Dialogs which do not exist anymore, so added optional chaining check to Dialog Refs. Also replaced changed DialogService to use ngMaterial's `openDialogs` array.

[DialogService]: add chaining check for Dialog refs

---

ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.directive.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.directive.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.stories.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/readme.mdx
ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
ngx-fudis/projects/ngx-fudis/src/public-api.ts

Jira: https://funidata.atlassian.net/browse/DS-404
Error Message Component doesn't have any HTML template, so it was unnecessary to keep it as Component. This PR changes it to Directive.
Breaking change migration:
- If application has imported `ErrorMessageComponent` from Fudis, it should now import `ErrorMessageDirective` instead

[Error Message]: Change component to directive

---

ngx-fudis/projects/dev/src/app/components/formExamples.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.directive.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/examples/form-example-with-multiple-forms.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/localized-text-group/localized-text-group.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/localized-text-group/localized-text-group.component.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/localized-text-group/localized-text-group.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/localized-text-group/localized-text-group.mdx
ngx-fudis/projects/ngx-fudis/src/lib/components/form/localized-text-group/localized-text-group.stories.ts
ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts
ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validator-utilities.spec.ts

Jira ticket: https://funidata.atlassian.net/browse/DS-432
App developers requested this feature to enable stricker typing. Discussion found here: https://sisudev.slack.com/archives/C03G46K6LG1/p1733216094386739
Breaking change migration:
- Renamed `FudisLocalizedTextGroup` to `FudisLocalizedTextGroupFormGroup` to follow naming convetions
- Now LocalizedTextGroupComponent now requires one type parameter. In most cases application can use default type provided by Fudis (`FudisLocalizedTextGroupDefaultFormGroup`) or their own type.

[Localized Text Group]: Type change

---

ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/mock_data.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-option-base/select-option-base.directive.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-option/multiselect-option.component.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-option/multiselect-option.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.ts

https://funidata.atlassian.net/browse/DS-446
- Internal function renamed from `_onLangChangeCheckIfLabelRequiresUpdate` to `_checkIfLabelRequiresUpdate`.
- Removed internal variable `_appLanguage`
- Now select component's input value is always updated if `data` input is changed

[SelectOption, MultiSelectOption]: Language change does not update the input value

---

ngx-fudis/projects/ngx-fudis/src/lib/directives/tooltip/tooltip.directive.ts
test/visual-regression/tooltip.spec.ts

https://funidata.atlassian.net/browse/DS-340
- Enable possibility to interact with tooltip content:
- Hover over the tooltip without it disappearing
- Copying text inside the tooltip
- Enable closing tooltip with `Esc`
- Add E2E tests (most of the functionality is tested here, instead of unit tests)
_Note:_ Known issue/feature coming from [ngMaterial Tooltip](https://material.angular.io/components/tooltip/overview) is that even though our own `tooltipToggle` is set to `true`, the tooltip element will disappear always after mouse leaves the `<mat-tooltip-component>`. This issue will be fixed when creating our own Popover Component without ngMaterial dependency.

[Tooltip]: Accessibility fixes

---

.github/dependabot.yaml
.github/workflows/cla.yaml
.github/workflows/delete_branch_docs.yaml
.github/workflows/publish_docs_from_pr.yaml
.github/workflows/release.yaml
.github/workflows/run_tests.yaml

I went through [Security hardening for GitHub Actions](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions) and reviewed our workflows to be on par with GitHub's instructions. Mostly, everything looks to be fine.
As a precaution, I pinned some third-party actions to SHA's instead of version tags or branches, as they were earlier. I figured the actions authored by GitHub, Docker, and AWS to be trusted and left those pinned on major versions to benefit from bug and vulnerability fixes, etc. For the actions that I pinned to SHA's, I did a really quick and light review on repository-level to check that there are no obvious reported vulnerabilities or other funny things going on. (Do not consider those actions to be vetted based …

Small updates to and hardening of GitHub Actions workflows

---

ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/label/label.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/label/label.component.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.spec.ts

https://funidata.atlassian.net/browse/DS-263
Update tests and update aria-invalid to true only after it has been marked as touched.
Additional ticket made about `ng-touched` not triggering OnPush components properly https://funidata.atlassian.net/browse/DS-475

[TextArea, TextInput, Label]: Update tests and fix aria-invalid visibility

---

ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.mdx
ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.html

https://funidata.atlassian.net/browse/DS-447
- Unify screen reader functionality so that it works similarly in LocalizedTextGroup and basic text inputs. 
- _"x/xx characters used"_ is now always read in its own block after helpText and not within helpText. 
- Threshold warning functionality stays the same.
- Added suggestion for Dialog's documentation about heading level

[Guidance]: Unify maxLength indicator screen reader prompts

---

ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.spec.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.stories.ts
ngx-fudis/projects/ngx-fudis/src/lib/directives/popover/popover.mdx
ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts

https://funidata.atlassian.net/browse/DS-476
- Fixed CSS class with `[size]="'icon-only'"` button
- `fudis-button__label--visible` --> `fudis-button__label--hidden`
- Removed popover controls from Button stories
- We don't want to enforce popover usage directly in button
- Two click events in one element is not accessible

[Button]: CSS class fix for icon-only button

---

ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/notification/readme.mdx
ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
test/visual-regression/error-summary.spec.ts

https://funidata.atlassian.net/browse/DS-476
- Changed attention text from aria-label to its own visually-hidden paragraph
- NVDA does not recognize native `article` element at all and therefore it does not announce any aria-attributes which are linked to that article element
- Mentioned about article use in Notification documentation
- Added missing Storybook control excules

[Notification]: Replace attention text from ARIA to its own hidden paragraph

---

ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/localized-text-group/localized-text-group.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.html
ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.html

https://funidata.atlassian.net/browse/DS-488
- Added missing `control.touched` checks for 
- Datepicker
- LocalizedTextGroup
- Multiselect
- Select
Screen reader was announcing input fields as invalid immediately when user focuses on them because there were missing `touched` checks.

[Form Components]: Add control's touched check

---

ngx-fudis/projects/ngx-fudis/src/lib/components/dropdown-menu/dropdown-menu.component.ts

https://funidata.atlassian.net/browse/DS-505
- Tested this hotfix in an example branch in client application side -> issue fixed
- Does not fix the root cause and is still found when detecting circular dependencies with [madge](https://github.com/pahen/madge)
- `madge --circular --extensions ts ngx-fudis/projects/ngx-fudis/src/`
- `lib/components/button/button.component.ts` > `lib/components/dropdown-menu/dropdown-menu.component.ts`
- There are three other issues and all of these shall be fixed in separate ticket/branch

[DropdownMenu]: HOTFIX circular dependency

---

.github/workflows/build_image.yaml
.github/workflows/run_tests.yaml

Apparently our increased usage of GitHub Actions has bloated the artifact storage. Some other repositories have been hitting the quota limit and it's shared across the organisation.
This PR especially limits the rather large Docker image to be retained for one day only (it is only needed during the test run so could be discarded immediately anyway). I also added `retention-period` to Playwright reports but it's the same as the current repository setting which `upload-artifact` defaults to, so doesn't really change anything expect makes the configuration more explicit.

Limit uploaded artifact retention period

---

ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-common/utilities.ts
ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.stories.ts

https://funidata.atlassian.net/browse/DS-479
In datepicker utilities functions, ensure that date input year value has 4 numbers. Otherwise show validation errors.
Also added more descriptive helptext to dateMin and dateMax validators, in order to produce errors.

[Datepicker, DateRange]: Date input parsing fix

---

ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.ts

https://funidata.atlassian.net/browse/DS-514
When DateRange has a pre set value from initialisation, check comparison errors in afterViewInit.

[DateRange]: Trigger date crossing check properly (even if other datepicker is not touched)

---

ngx-fudis/projects/documentation/introduction/GettingStarted.mdx
ngx-fudis/projects/ngx-fudis/package-lock.json
ngx-fudis/projects/ngx-fudis/package.json

https://funidata.atlassian.net/browse/DS-544
- Changed semver syntax for peerDependencies
- We want to allow the consuming app to have newer Angular major version
- Added documentation about recommended Angular and Angular Material versions
- Even though we allow newer major version to be used, we do not guarantee the compatibility

[PeerDependencies]: Change semver syntax to allow newer major versions

---

.github/release.yml
.github/workflows/release.yaml

https://funidata.atlassian.net/browse/DS-486
In [this PR](https://github.com/funidata/fudis/pull/610), there were changes to Github release workflow but there was one missing path fix
- **fudis.funidata.fi** root URL should not redirect to Ngx Storybook anymore
- Root URL will redirect to the new landing page (WIP in Core repo, [PR](https://github.com/funidata/fudis-core/pull/39))
- Only **fudis.funidata.fi/ngx** should redirect to the latest deployed Ngx Storybook version
Extra:
- Also noticed that our Github Actions label is missing from the Github release labels which are used to categorize pull requests in Github release notes.

[Storybook]: URL redirect path

---

.github/workflows/release.yaml

https://funidata.atlassian.net/browse/INFRA-1753
This change fixes URL's fudis.funidata.fi/ngx/ and fudis.funidata.fi/ngx/v/ which currently do not redirect to latest docs but rather return HTTP 403.

Create redirect objects in /ngx child paths when publishing docs

---

.github/workflows/run_tests.yaml
test/playwright.config.ts

https://funidata.atlassian.net/browse/DS-523
This PR modifies the Playwright test setup so that the tests are run in parallel in CI. This does not affect running tests locally. I use GitHub's matrix strategy and Playwrights sharding feature to split the tests into four groups and run them on different workflow runners. After the shards have completed, I combine the shard-specific blob reports into a single report.
> [!NOTE]
> Branch protection settings must be updated to require the new tests before a PR is merged. (The test names change and there is now one test per shard.)
> [!TIP]
> The blob reports are JSON and not nicely readable. When a shard fails, it's easier to wait until the combined report has been generated.

Run VR tests in parallel to reduce CI run duration

---

.github/workflows/run_tests.yaml

https://funidata.atlassian.net/browse/DS-574
- Added suggested log output for visual-regression-test job
- Log only when failure occurs
- Add hard-coded container name, otherwise it will have randomized name and cannot be called by `docker logs`

[GithubActions]: Log output for failed vr job
